---
apiVersion: v1
kind: Namespace
metadata:
  name: nearrtric
  labels:
    name: nearrtric
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2term
  namespace: nearrtric
  labels:
    app: e2term
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2term
  template:
    metadata:
      labels:
        app: e2term
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/reg
                    operator: Exists
      containers:
        - name: e2term
          image: "{{ host_internal_ip }}:5000/o-ran-sc/ric-plt-e2"
          imagePullPolicy: Always
          command: 
            - /scripts/e2term.sh
          env:
            - name: CONTAINER_NAME
              value: ric_e2term
            - name: HOST_NAME
              value: ric_e2term_host
            - name: POD_NAME
              value: e2term_pod
            - name: SERVICE_NAME
              value: ric_e2term_service
            - name: print
              value: "1"
            - name: RMR_SEED_RT
              value: /opt/e2/dockerRouter.txt
            #- name: RMR_SRC_ID # IP kontenera ustanawiane w skrypcie
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /configs
              name: configs
      volumes:
        - name: scripts
          hostPath:
            path: "{{ data_dir }}/volumes/scripts"
            type: Directory
        - name: configs
          hostPath:
            path: "{{ data_dir }}/volumes/configs"
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: e2term
  namespace: nearrtric
spec:
  type: ClusterIP
  selector:
    app: e2term
  ports:
    - name: e2
      protocol: SCTP
      port: 36421
      targetPort: 36421
    - name: "38000"
      protocol: TCP
      port: 38000
      targetPort: 38000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: e2term
  namespace: nearrtric
spec:
  podSelector:
    matchLabels:
      app: e2term
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nearrtric
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gnb
      ports:
        - protocol: SCTP
          port: 36421
        - protocol: TCP
          port: 38000
