---
apiVersion: v1
kind: Service
metadata:
  name: "srsdu-f1u-service"
spec:
  type: ClusterIP
  selector:
    app: "srsdu"
  ports:
    - name: "f1u"
      protocol: "UDP"
      port: 2152
      targetPort: 2152
