---
- name: "Add necessary kernel modules"
  community.general.modprobe:
    name: sch_netem
    state: present

- name: "Remove root qdisc"
  ansible.builtin.command:
    cmd: "tc qdisc del dev {{ vm_internal_network_interface }} root"
  register: out
  changed_when: out.rc == 0
  failed_when: out.rc != 0
  ignore_errors: true

- name: "Make root htb qdisc"
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    - "tc qdisc add dev {{ vm_internal_network_interface }} root handle 1: htb default 10"
    - "tc class add dev {{ vm_internal_network_interface }} parent 1: classid 1:1 htb rate 1000mbit"
    - "tc class add dev {{ vm_internal_network_interface }} parent 1:1 classid 1:10 htb rate 1000mbit"
  register: out
  changed_when: out.rc == 0
  failed_when: out.rc != 0
  when: remove_tc is not defined or not remove_tc

- name: "Include task: tc_reg"
  ansible.builtin.include_tasks: tc_reg.yml
  with_items: "{{ tc_latency | dict2items | sort(attribute='key') }}"
  loop_control:
    loop_var: top_region
    index_var: top_region_index
  when: top_region.key == region and (remove_tc is not defined or not remove_tc)
