---
core_git_repo: https://github.com/KedArch/open5gs
core_git_version: v2.6.0
core_pkg_deps:
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - ninja-build
  - build-essential
  - flex
  - bison
  - git
  - cmake
  - meson
  - libsctp-dev
  - libgnutls28-dev
  - libgcrypt-dev
  - libssl-dev
  - libidn11-dev
  - libmongoc-dev
  - libbson-dev
  - libyaml-dev
  - libmicrohttpd-dev
  - libcurl4-gnutls-dev
  - libnghttp2-dev
  - libtins-dev
  - libtalloc-dev
  - iproute2
  - ca-certificates
  - netbase
  - pkg-config
  - software-properties-common
core_nf_list:
  - amf
  - ausf
  - bsf
  - nrf
  - nssf
  - pcf
  - scp
  - smf
  - udm
  - udr
core_dbctl_url: https://raw.githubusercontent.com/KedArch/open5gs/main/misc/db/open5gs-dbctl
