---
manifests_repo: mgr
manifests_orchestrator_apply:
  k3s:
    template: k8s.yaml.j2
    command: kubectl apply -f
  nomad:
    template: nomad.hcl.j2
    command: nomad job run
manifests_list:
  - component: srscu
    cmd: /script.sh
    ports:
      - name: "F1AP"
        type: SCTP
        number: 38472
      - name: "F1U"
        type: UDP
        number: 2152
    nodeports:
      - name: "CORE"
        type: UDP
        number: 2152
    env:
      AMF_ADDR: "{{ hostvars[core]['ansible_host'] }}"
    affinity: reg
    volumes:
      - name: script
        host: "{{ data_dir }}/volumes/scripts/srscu.sh"
        dest: "/script.sh"
      - name: config-in
        host: "{{ data_dir }}/volumes/configs/srscu.yaml.in"
        dest: "/etc/srscu.yaml.in"

  - component: srsdu
    cmd: /script.sh
    ports:
      - name: "F1AP"
        type: SCTP
        number: 38472
      - name: "F1U"
        type: UDP
        number: 2152
    nodeports:
      - name: "ZMQ"
        type: TCP
        number: 2000
    env:
      CU_CP_ADDR: srscu-f1ap-service
      UE_ADDR: "{{ hostvars[ue]['ansible_host'] }}"
    affinity: edge
    volumes:
      - name: script
        host: "{{ data_dir }}/volumes/scripts/srsdu.sh"
        dest: "/script.sh"
      - name: config-in
        host: "{{ data_dir }}/volumes/configs/srsdu.yaml.in"
        dest: "/etc/srsdu.yaml.in"
