cu_cp:
  amf:
    addr: AMF_ADDR
    bind_addr: CORE_BIND_ADDR
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  f1ap:
    bind_addr: 0.0.0.0
  inactivity_timer: 7200
cu_up:
  f1u:
    socket:
      -
        bind_addr: 127.0.0.1
        ext_addr: F1U_EXT_ADDR
log:
  all_level: debug
e2:
  enable_cu_cp_e2: true
  enable_cu_up_e2: true
  e2sm_kpm_enabled: true
  e2sm_rc_enabled: true
  addr: e2term.nearrtric.svc.cluster.local
  port: 36421
  bind_addr: 0.0.0.0
log:
  e2ap_level: debug
metrics:
  enable_log: false
  enable_json: false
  periodicity:
    cu_up_report_period: 1000
    cu_cp_report_period: 1000
  layers:
    enable_pdcp: false
