apiVersion: v1
kind: Pod
metadata:
  name: ram-stress-pod
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: ram-stress
      image: 10.200.0.1:5000/ram_stress
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "8Gi"
          cpu: "1000m"
  restartPolicy: Never
