---
- name: "Create partition on additional disk"
  community.general.parted:
    device: /dev/vdb
    number: 1
    flags: []
    state: present

- name: "Create filesystem on additional disk"
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdb1

- name: "Mount partition on additional disk"
  ansible.posix.mount:
    fstype: ext4
    src: /dev/vdb1
    path: "{{ data_dir if vms_data_path is not defined else vms_data_path }}"
    state: mounted
