---
- name: "Disable ufw"
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false

- name: "Include task: filesystem"
  ansible.builtin.include_tasks: filesystem.yml

- name: "Add proxy to environment"
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { "key": "http_proxy", "value": "http://{{ host_internal_ip }}:{{ squid_port }}" }
    - { "key": "https_proxy", "value": "http://{{ host_internal_ip }}:{{ squid_port }}" }
    - { "key": "no_proxy", "value": "localhost,127.0.0.1,{{ host_vm_network }}" }
