FROM base:latest

COPY --from=builder:latest /srsRAN/build/apps/{{ app }}/srs{{ app }} /usr/bin/srs{{ app }}

{% if app == 'cu' %}
RUN apt update \
    && apt install -y \
        iproute2 \
        iptables \
    && apt-get clean
{% endif %}

CMD /usr/bin/srs{{ app }} -c /etc/srs{{ app }}.yaml