FROM ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    {% for pkg in gnb_pkg_deps -%} 
      {{ pkg }} \
    {% endfor -%}
    && apt-get clean
