---
- name: "Create LV for images"
  become: true
  community.general.lvol:
    vg: ubuntu-vg
    lv: images
    size: 360G
    force: true
    resizefs: true

- name: "Create filesystem on LV"
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: /dev/mapper/ubuntu--vg-images

- name: "Mount LV"
  become: true
  ansible.posix.mount:
    path: /var/lib/libvirt/images
    src: /dev/mapper/ubuntu--vg-images
    fstype: ext4
    state: mounted
    opts: defaults
