---
- name: "Create nginx config"
  ansible.builtin.copy:
    dest: /etc/nginx/sites-enabled/base-image
    content: |
      server {
        listen {{ nginx_port }};
        listen [::]:{{ nginx_port }};
        root {{ host_nginx_cache_path }};
      }
    mode: "755"
  register: nginx_conf

- name: "Ensure directory exists"
  ansible.builtin.file:
    path: "{{ host_nginx_cache_path }}"
    state: directory
    mode: "755"

- name: "Ensure nginx is started and enabled"
  ansible.builtin.service:
    name: nginx
    state: "{{ 'restarted' if nginx_conf.changed else 'started' }}"
    enabled: true

- name: Allow Nginx traffic through the firewall
  community.general.ufw:
    rule: allow
    port: "{{ nginx_port }}"
    proto: tcp
