---
- name: "Apply manifest: {{ item | basename }}" # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "kubectl apply -f {{ data_dir }}/manifests/{{ manifests_orchestrator }}/{{ item | basename }}"
