---
- name: "Filter valid nodes"
  ansible.builtin.include_tasks: proceeding.yml
  when: >
    inventory_hostname in groups[manifests_cp_node_group]
    or inventory_hostname in groups[manifests_worker_node_group]
