---
- name: "Copy manifest: {{ item | basename }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ data_dir }}/manifests/{{ item | basename }}"
    mode: "640"

- name: "Apply manifest: {{ item | basename }}" # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "{{ command }} {{ data_dir }}/manifests/{{ item | basename }}"
