---
- name: "Copy template"
  ansible.builtin.template:
    src: "{{ template }}"
    dest: "{{ data_dir }}/manifests/{{ item.component }}.{{ template.split('.')[-2] }}"
    mode: "640"
  vars:
    component: "{{ item.component }}"
    cmd: "{{ item.cmd }}"
    affinity: "{{ item.affinity }}"
    env: "{{ item.env }}"
    ports: "{{ item.ports }}"
    nodeports: "{{ item.nodeports }}"
    volumes: "{{ item.volumes }}"

- name: "Apply manifest" # noqa: no-changed-when
  ansible.builtin.command:
    cmd: "{{ command }} {{ data_dir }}/manifests/{{ item.component }}.{{ template.split('.')[-2] }}"
