apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  containers:
  - name: cpu-stress
    image: busybox
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "4000m"
    command: ["sh", "-c", "while true; do :; done"]
  restartPolicy: Never

