apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: cpu-stress
      image: 10.200.0.1:5000/cpu_stress
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "4000m"
  restartPolicy: Never

