---
- name: "Include task: install_binary"
  ansible.builtin.include_tasks: install_binary.yml

- name: "Include task: paths"
  ansible.builtin.include_tasks: paths.yml

- name: "Copy node config files"
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}/node_config.hcl"
    mode: "640"
  with_items:
    - {"template": "node_nomad_config.hcl.j2", "dest": "{{ nomad_conf_path }}"}
    - {"template": "node_consul_config.hcl.j2", "dest": "{{ consul_conf_path }}"}
  register: config

- name: "Copy service files"
  ansible.builtin.template:
    src: "service.service.j2"
    dest: "/etc/systemd/system/{{ item.service }}.service"
    mode: "644"
  vars:
    service: "{{ item.service }}"
    exec: "{{ item.exec }}"
  with_items:
    - {"service": "nomad", "exec": "nomad agent -config={{ nomad_conf_path }}/node_config.hcl"}
    - {"service": "consul", "exec": "consul agent -config-file={{ consul_conf_path }}/node_config.hcl"}
  register: service

- name: "Copy docker daemon config"
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: "644"
  register: docker

- name: "Start services"
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    daemon_reload: true
    state: "{{ 'restarted' if (config.changed or service.changed or docker.changed) else 'started' }}"
  with_items:
    - nomad
    - consul
    - docker

- name: "Include task: cilium"
  ansible.builtin.include_task: cilium.yml

