- name: "Get k3s kubeconfig"
  hosts: localhost
  tasks:
    - name: "Ensure creds dir exists"
      ansible.builtin.file:
        path: "creds"
        state: directory
        mode: "750"
    - name: "Download k3s kubeconfig"
      delegate_to: "{{ first_cp_node }}"
      become: true
      ansible.builtin.slurp:
        path: "{{ data_dir }}/rancher/conf/k3s/k3s.yaml"
      register: config
    - name: "Save to file"
      ansible.builtin.copy:
        content: "{{ config.content | b64decode | trim }}"
        dest: "creds/kubeconfig"
        mode: "640"
