---
- name: "Configure k3s"
  hosts: "{{ ansible_limit | default(['control', 'worker']) }}"
  become: true
  pre_tasks:
    - name: "Disable Nomad if running" # noqa: no-changed-when ignore-errors
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - nomad
        - consul
        - docker
      ignore_errors: true
      when: k3s_uninstall is not defined or not k3s_uninstall
    - name: "Clear firewall" # noqa: no-changed-when
      ansible.builtin.command: nft flush ruleset
      when: nomad_uninstall is not defined or not nomad_uninstall
    - name: "Write state change to file"
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        content: "k3s"
        dest: "state"
        mode: "644"
      when: k3s_uninstall is not defined or not k3s_uninstall
  roles:
    - role: vms
      when: skip_vms is not defined or not skip_vms
    - role: k3s
      vars:
        k3s_root_path: "{{ data_dir }}"
        k3s_first_cp_node: "{{ first_cp_node }}"
        k3s_cp_node_group: "{{ cp_node_group }}"
        k3s_worker_node_group: "{{ worker_node_group }}"
