---
- name: "Include playbook: vms"
  ansible.builtin.import_playbook: vms.yml
  when: >
    (k3s_uninstall is not defined or not k3s_uninstall)
    and (skip_vms is not defined or not skip_vms)

- name: "Configure k3s"
  hosts: "{{ ansible_limit | default('vms') }}"
  become: true
  pre_tasks:
    - name: "Disable Nomad if running" # noqa: no-changed-when ignore-errors
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - nomad
        - consul
        - docker
      ignore_errors: true
    - name: "Write state change to file"
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        content: "k3s"
        dest: "state"
        mode: "644"
  roles:
    - role: k3s
      k3s_root_path: "{{ data_dir }}"
      k3s_first_cp_node: "{{ first_cp_node }}"
      k3s_cp_node_group: "{{ cp_node_group }}"
      k3s_worker_node_group: "{{ worker_node_group }}"
