---
- name: "Include playbook: vms"
  ansible.builtin.import_playbook: vms.yml
  when: >
    (k3s_uninstall is not defined or not k3s_uninstall)
    and (skip_vms is not defined or not skip_vms)

- name: "Configure k3s"
  hosts: "{{ ansible_limit | default('vms') }}"
  become: true
  roles:
    - role: k3s
      k3s_root_path: "{{ data_dir }}"
      k3s_first_cp_node: "{{ first_cp_node }}"
      k3s_cp_node_group: "{{ cp_node_group }}"
      k3s_worker_node_group: "{{ worker_node_group }}"
