- name: "Prepare vms"
  hosts: vms
  become: true
  tasks:
    - name: "Disable ufw"
      ansible.builtin.service:
        name: ufw
        state: stopped
    - name: "Create partition"
      community.general.parted:
        device: /dev/vdb
        number: 1
        flags: [ ]
        state: present
    - name: "Create filesystem"
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vdb1
    - name: "Mount partition"
      ansible.posix.mount:
        fstype: ext4
        src: /dev/vdb1
        path: "{{ '/var/lib' if vms_data_path is not defined else vms_data_path }}"
        state: mounted
